name: Deploy static content to Pages

on:
  push:    
  workflow_dispatch:

permissions:
  contents: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

jobs:
  deploy:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Setup Pages
      #   uses: actions/configure-pages@v4

      # - name: Install runtime
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18

      # - name: Install dependencies
      #   run: npm install -g @koumoul/gh-pages-multi

      - name: Generate example page
        run: |
          mkdir -p build
          echo "<h1>Hello, world! ${{ github.sha }}</h1>" > build/index.html

      # - name: Github config
      #   run: |
      #     git config --global user.email "wwasowicz@taskrabbit.com"
      #     git config --global user.name "wwwasowicz"

      # - name: Deploy
      #   run: gh-pages-multi deploy -s dist -t ${{ github.sha }}

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ github.token }}
          TARGET_DIR: ${{ github.sha }}
